dxfrontier/dx-starter-templates

- .projenrc.ts
> deps: add forgotten peerDeps

- src/GitHubActionProject.ts
- src/GitHubManager.ts
> doc: clean up documentation

- src/GitHubActionProject.ts
> feature: remove unnecessary options

- src/GitHubActionProject.ts
- src/builder/GitHubBuilder.ts
- src/index.ts
> feature: remove managers and add builders

- src/templates/github/bugIssue.ts
- test/gitHubActionProject.test.ts
> 31 feature housekeeping align code to prettify standards

- src/templates/github/bugIssue.ts
- src/templates/github/featureIssue.ts
- src/templates/github/questionIssue.ts
> doc: align templates function doc

- src/builder/GitHubBuilder.ts
> doc: aligned class method docs

- src/GitHubActionProject.ts
- src/builder/NpmPackageBuilder.ts
- src/constants/templates.ts
- src/types/common.ts
- test/gitHubActionProject.test.ts
> 5 feature housekeeping packagejson content

- src/GitHubActionProject.ts
- src/index.ts
> refactoring: minor codebase changes

- .projenrc.ts
- src/index.ts
> refactor: minor codebase changes

- .projenrc.ts
- src/GitHubActionProject.ts
- src/builder/DevContainerBuilder.ts
- src/builder/VsCodeBuilder.ts
> 54 feature housekeeping align calls method names according to their function

- .gitignore
- .projen/tasks.json
- .projenrc.ts
- src/GitHubActionProject.ts
- src/components/index.ts
> 56 feature housekeeping standardize add scripts across all builders

- src/components/NpmPackageComponent.ts
- test/gitHubActionProject.test.ts
> 62 feature define relevant files for npm package

- .github/ISSUE_TEMPLATE/bug.yml
- src/components/GitHubComponent.ts
- test/gitHubActionProject.test.ts
> 69 feature housekeeping align bug template title with other template titles

- test/gitHubActionProject.test.ts
> refactor: test prettier npm scripts for correct command

- test/gitHubActionProject.test.ts
> 68 bug tests for gitattributes are malfromed

- src/components/CommitLintComponent.ts
- src/types/script.ts
- test/gitHubActionProject.test.ts
- test/util.ts
> 76 feature housekeeping add util function for npm scripts tests

- .projen/deps.json
- .projen/tasks.json
- package-lock.json
- package.json
- src/components/CommitLintComponent.ts
- src/components/HuskyComponent.ts
- src/types/component.ts
- test/gitHubActionProject.test.ts
> 81 bug devdependencies are missing

- src/GitHubActionProject.ts
- src/components/CommitLintComponent.ts
- src/components/DevContainerComponent.ts
- src/components/GitHubComponent.ts
- src/components/HuskyComponent.ts
- src/components/NpmPackageComponent.ts
- src/components/PrettierComponent.ts
- src/components/VsCodeComponent.ts
- src/types/general.ts
- src/types/index.ts
- test/gitHubActionProject.test.ts
> refactor(types): aligned imports

- src/GitHubActionProject.ts
- src/components/CommitLintComponent.ts
- src/components/DevContainerComponent.ts
- src/components/GitHubComponent.ts
- src/components/HuskyComponent.ts
- src/components/NpmPackageComponent.ts
- src/components/PrettierComponent.ts
- src/components/VsCodeComponent.ts
- src/types/index.ts
- test/gitHubActionProject.test.ts
> refactor(reapply): aligned imports

- src/components/CommitLintComponent.ts
- src/components/DevContainerComponent.ts
- src/components/GitHubComponent.ts
- src/components/HuskyComponent.ts
- src/components/NpmPackageComponent.ts
- src/components/PrettierComponent.ts
- src/components/VsCodeComponent.ts
> docs(component): align spelling of descriptions

- test/gitHubActionProject.test.ts
> fix(component): added missing .gitattributes entries

- src/jsii/commitlint.ts
> refactor(cleansing): removed local test code

- src/cap-service/project.ts
- src/util/utils.ts
> refactor(project.ts): removed unused code from cap-service

- README.md
> chore(readme): updated main readme

- cliff.toml
> fix(cliff): releases should be fixed after cliff template is fixed

- .github/dev-to-main.md
- .github/workflows/pr-template-switch.yml
> fix: changes

- CHANGELOG.md
- package-lock.json
- package.json
> ci: bump version, CHANGELOG.md generated (#265)
